// Demo data for when Supabase is not configured

export const demoCategories = [
  { id: '1', name: 'Construction Equipment', description: 'Heavy machinery and tools for construction projects' },
  { id: '2', name: 'Power Tools', description: 'Electric and battery-powered tools' },
  { id: '3', name: 'Garden & Landscaping', description: 'Tools and machinery for gardening and landscaping' },
  { id: '4', name: 'Utes & Vehicles', description: 'Dual cab utes and commercial vehicles for transport' },
]

export const demoEquipment = [
  {
    id: '2',
    category_id: '1',
    name: 'Forklift 3.5t',
    description: 'Heavy duty forklift for material handling and warehouse operations',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 3,
    available_quantity: 3,
    specifications: { capacity: '3500kg', lift_height: '4.5m', fuel_type: 'diesel', fork_length: '1.2m' },
    images: ['/images/equipment/construction/forklift-3-5t.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '11',
    category_id: '1',
    name: 'Kubota M7-2 Deluxe Tractor',
    description: 'Premium agricultural tractor with advanced features for farming and construction',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { power: '170HP', transmission: 'CVT', pto: '540/1000 rpm', hydraulic_capacity: '110L/min' },
    images: ['/images/equipment/construction/kubota-m7-2-deluxe.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '12',
    category_id: '1',
    name: 'Toro TX 1000 Compact Loader',
    description: 'High-capacity compact track loader for tight spaces and heavy loads',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { operating_capacity: '1000kg', engine: '35HP', width: '90cm', tipping_load: '2000kg' },
    images: ['/images/equipment/construction/toro-tx-1000.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '15',
    category_id: '1',
    name: 'Kubota M100/M110GX',
    description: 'Versatile utility tractor for agricultural and construction applications',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { power: '100-110HP', transmission: '24-speed', pto: '540/1000 rpm', lift_capacity: '3100kg' },
    images: ['/images/equipment/construction/kubota-m100-m110gx.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '16',
    category_id: '1',
    name: 'PT300 Forestry Mulcher',
    description: 'Heavy-duty tracked forestry mulcher for land clearing and vegetation management',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 1,
    available_quantity: 1,
    specifications: { power: '300HP', cutting_width: '2.5m', tracks: 'steel', mulching_capacity: '300mm diameter' },
    images: ['/images/equipment/construction/pt300-mulcher.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '17',
    category_id: '1',
    name: 'RCU120 Remote Controlled Tracked Carrier',
    description: 'Remote controlled tracked carrier for difficult terrain and hazardous areas',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 1,
    available_quantity: 1,
    specifications: { power: '120HP', payload: '1200kg', control_range: '500m', slope_capacity: '45 degrees' },
    images: ['/images/equipment/construction/rcu120-tracked-carrier.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '18',
    category_id: '1',
    name: 'Bobcat TL35.70 Telehandler',
    description: 'Versatile telehandler for material handling at height',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { lift_capacity: '3500kg', lift_height: '7m', reach: '3.7m', engine: '100HP' },
    images: ['/images/equipment/construction/bobcat-tl35-70-telehandler.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '19',
    category_id: '1',
    name: 'Bobcat TL38.70HF Telehandler',
    description: 'High-flow telehandler with superior hydraulic performance',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 1,
    available_quantity: 1,
    specifications: { lift_capacity: '3800kg', lift_height: '7m', reach: '3.9m', engine: '130HP' },
    images: ['/images/equipment/construction/bobcat-tl38-70hf-telehandler.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '20',
    category_id: '1',
    name: 'Bobcat S76 Skid-Steer Loader',
    description: 'Compact and powerful skid-steer loader for versatile job site tasks',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 3,
    available_quantity: 3,
    specifications: { operating_capacity: '1750kg', engine: '74HP', width: '1.8m', bucket_capacity: '0.5m³' },
    images: ['/images/equipment/construction/bobcat-s76-skid-steer.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '21',
    category_id: '1',
    name: 'Bobcat E10 Mini Excavator',
    description: 'Ultra-compact mini excavator ideal for tight spaces and indoor work',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { operating_weight: '1160kg', dig_depth: '1.82m', engine: '10.2HP', width: '0.71m' },
    images: ['/images/equipment/construction/bobcat-e10-mini-excavator.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '22',
    category_id: '1',
    name: 'Hamm HC 50i Compactor',
    description: 'Intelligent soil compactor with automatic compaction control',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { operating_weight: '5000kg', drum_width: '1.4m', engine: '55HP', compaction_force: '60kN' },
    images: ['/images/equipment/construction/hamm-hc-50i-roller.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '23',
    category_id: '1',
    name: 'Hamm HC 70i Compactor',
    description: 'Heavy-duty intelligent compactor for large-scale projects',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { operating_weight: '7000kg', drum_width: '1.68m', engine: '75HP', compaction_force: '90kN' },
    images: ['/images/equipment/construction/hamm-hc-70i-roller.png'],
    status: 'active',
    categories: { name: 'Construction Equipment' }
  },
  {
    id: '3',
    category_id: '2',
    name: 'CAT C1.1 Generator (60 Hz)',
    description: 'Compact diesel generator for reliable power supply',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 4,
    available_quantity: 4,
    specifications: { power_output: '9.5kVA', frequency: '60Hz', fuel_type: 'diesel', runtime: '8 hours' },
    images: ['/images/equipment/power-tools/cat-generator-c1-1.png'],
    status: 'active',
    categories: { name: 'Power Tools' }
  },
  {
    id: '9',
    category_id: '2',
    name: 'CAT C1.1 | DE7.5E3S Generator',
    description: 'Diesel generator with enhanced capacity for construction sites',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 3,
    available_quantity: 3,
    specifications: { power_output: '7.5kVA', frequency: '50Hz', fuel_type: 'diesel', runtime: '10 hours' },
    images: ['/images/equipment/power-tools/cat-generator-de7-5e3s.png'],
    status: 'active',
    categories: { name: 'Power Tools' }
  },
  {
    id: '10',
    category_id: '3',
    name: 'LV600 PRO Remote Controlled Mower',
    description: 'Professional remote controlled mower for steep slopes and difficult terrain',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { cutting_width: '600mm', slope_capacity: '55 degrees', control_range: '300m', fuel_type: 'petrol' },
    images: ['/images/equipment/landscaping/lv600-pro-mower.png'],
    status: 'active',
    categories: { name: 'Garden & Landscaping' }
  },
  {
    id: '13',
    category_id: '3',
    name: 'Toro Groundsmaster 4000D',
    description: 'Commercial wide-area rotary mower for large turf areas',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 1,
    available_quantity: 1,
    specifications: { cutting_width: '11 feet', engine: '55HP turbo diesel', decks: '5 cutting units', fuel_capacity: '68L' },
    images: ['/images/equipment/landscaping/toro-groundsmaster-4000d.png'],
    status: 'active',
    categories: { name: 'Garden & Landscaping' }
  },
  {
    id: '14',
    category_id: '3',
    name: 'Z Master 60"',
    description: 'Commercial zero-turn mower with 60-inch cutting deck',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 3,
    available_quantity: 3,
    specifications: { cutting_width: '60 inches', engine: '31HP', speed: '13mph', fuel_type: 'petrol' },
    images: ['/images/equipment/landscaping/toro-z-master-60.png'],
    status: 'active',
    categories: { name: 'Garden & Landscaping' }
  },
  {
    id: '4',
    category_id: '4',
    name: 'Dual Cab Ute',
    description: 'Versatile dual cab ute perfect for work sites and equipment transport',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 4,
    available_quantity: 4,
    specifications: { towing_capacity: '3500kg', payload: '1000kg', seats: '5', fuel_type: 'diesel' },
    images: ['/images/equipment/vehicles/dual-cab-ute.png'],
    status: 'active',
    categories: { name: 'Utes & Vehicles' }
  },
  {
    id: '5',
    category_id: '4',
    name: 'Dual Cab Tray Ute',
    description: 'Heavy duty dual cab ute with aluminum tray for maximum cargo capacity',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 3,
    available_quantity: 3,
    specifications: { towing_capacity: '3500kg', payload: '1400kg', seats: '5', tray_length: '2.4m' },
    images: ['/images/equipment/vehicles/dual-cab-tray-ute.png'],
    status: 'active',
    categories: { name: 'Utes & Vehicles' }
  },
  {
    id: '6',
    category_id: '4',
    name: 'NLR 45-150 AMT Tipper',
    description: 'Medium duty tipper truck for construction and waste removal',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { gvm: '4500kg', payload: '2500kg', tipper_capacity: '4m³', transmission: 'AMT' },
    images: ['/images/equipment/vehicles/nlr-tipper.png'],
    status: 'active',
    categories: { name: 'Utes & Vehicles' }
  },
  {
    id: '7',
    category_id: '4',
    name: 'FRR 110-240 AMT Tipper',
    description: 'Heavy duty tipper truck for large construction and mining projects',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { gvm: '11000kg', payload: '6500kg', tipper_capacity: '8m³', transmission: 'AMT' },
    images: ['/images/equipment/vehicles/frr-tipper.png'],
    status: 'active',
    categories: { name: 'Utes & Vehicles' }
  },
  {
    id: '8',
    category_id: '4',
    name: 'FSR 140-260 Tipper',
    description: 'Heavy duty tipper truck with high payload capacity for demanding applications',
    daily_rate: null,
    weekly_rate: null,
    monthly_rate: null,
    total_quantity: 2,
    available_quantity: 2,
    specifications: { gvm: '14000kg', payload: '8500kg', tipper_capacity: '10m³', transmission: 'Manual' },
    images: ['/images/equipment/vehicles/fsr-tipper.png'],
    status: 'active',
    categories: { name: 'Utes & Vehicles' }
  }
]